<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ForMenu.png" />
    <None Remove="logo.png" />
    <None Remove="Снимок экрана 2025-10-18 201133.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ForMenu.png" />
    <Resource Include="logo.png" />
  </ItemGroup>

</Project>
